// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/eliza.proto

package com.example.android.protobuftest.proto.connectrpc.eliza.v1;

public interface ConverseResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connectrpc.eliza.v1.ConverseResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sentence = 1 [json_name = "sentence"];</code>
   * @return The sentence.
   */
  java.lang.String getSentence();
  /**
   * <code>string sentence = 1 [json_name = "sentence"];</code>
   * @return The bytes for sentence.
   */
  com.google.protobuf.ByteString
      getSentenceBytes();
}
