// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/eliza.proto

package com.example.android.protobuftest.proto.connectrpc.eliza.v1;

public final class ElizaProto {
  private ElizaProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connectrpc_eliza_v1_SayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connectrpc_eliza_v1_SayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connectrpc_eliza_v1_SayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connectrpc_eliza_v1_SayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connectrpc_eliza_v1_ConverseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connectrpc_eliza_v1_ConverseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connectrpc_eliza_v1_ConverseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connectrpc_eliza_v1_ConverseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connectrpc_eliza_v1_IntroduceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connectrpc_eliza_v1_IntroduceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connectrpc_eliza_v1_IntroduceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connectrpc_eliza_v1_IntroduceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/eliza.proto\022\023connectrpc.eliza.v1" +
      "\"(\n\nSayRequest\022\032\n\010sentence\030\001 \001(\tR\010senten" +
      "ce\")\n\013SayResponse\022\032\n\010sentence\030\001 \001(\tR\010sen" +
      "tence\"-\n\017ConverseRequest\022\032\n\010sentence\030\001 \001" +
      "(\tR\010sentence\".\n\020ConverseResponse\022\032\n\010sent" +
      "ence\030\001 \001(\tR\010sentence\"&\n\020IntroduceRequest" +
      "\022\022\n\004name\030\001 \001(\tR\004name\"/\n\021IntroduceRespons" +
      "e\022\032\n\010sentence\030\001 \001(\tR\010sentence2\234\002\n\014ElizaS" +
      "ervice\022M\n\003Say\022\037.connectrpc.eliza.v1.SayR" +
      "equest\032 .connectrpc.eliza.v1.SayResponse" +
      "\"\003\220\002\001\022]\n\010Converse\022$.connectrpc.eliza.v1." +
      "ConverseRequest\032%.connectrpc.eliza.v1.Co" +
      "nverseResponse\"\000(\0010\001\022^\n\tIntroduce\022%.conn" +
      "ectrpc.eliza.v1.IntroduceRequest\032&.conne" +
      "ctrpc.eliza.v1.IntroduceResponse\"\0000\001B\266\001\n" +
      ":com.example.android.protobuftest.proto." +
      "connectrpc.eliza.v1B\nElizaProtoP\001\242\002\003CEX\252" +
      "\002\023Connectrpc.Eliza.V1\312\002\023Connectrpc\\Eliza" +
      "\\V1\342\002\037Connectrpc\\Eliza\\V1\\GPBMetadata\352\002\025" +
      "Connectrpc::Eliza::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_connectrpc_eliza_v1_SayRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_connectrpc_eliza_v1_SayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connectrpc_eliza_v1_SayRequest_descriptor,
        new java.lang.String[] { "Sentence", });
    internal_static_connectrpc_eliza_v1_SayResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_connectrpc_eliza_v1_SayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connectrpc_eliza_v1_SayResponse_descriptor,
        new java.lang.String[] { "Sentence", });
    internal_static_connectrpc_eliza_v1_ConverseRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_connectrpc_eliza_v1_ConverseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connectrpc_eliza_v1_ConverseRequest_descriptor,
        new java.lang.String[] { "Sentence", });
    internal_static_connectrpc_eliza_v1_ConverseResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_connectrpc_eliza_v1_ConverseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connectrpc_eliza_v1_ConverseResponse_descriptor,
        new java.lang.String[] { "Sentence", });
    internal_static_connectrpc_eliza_v1_IntroduceRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_connectrpc_eliza_v1_IntroduceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connectrpc_eliza_v1_IntroduceRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_connectrpc_eliza_v1_IntroduceResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_connectrpc_eliza_v1_IntroduceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connectrpc_eliza_v1_IntroduceResponse_descriptor,
        new java.lang.String[] { "Sentence", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
