// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/eliza.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.android.protobuftest.proto.connectrpc.eliza.v1;

