// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/eliza.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.android.protobuftest.proto.connectrpc.eliza.v1;

@kotlin.jvm.JvmName("-initializeintroduceRequest")
public inline fun introduceRequest(block: com.example.android.protobuftest.proto.connectrpc.eliza.v1.IntroduceRequestKt.Dsl.() -> kotlin.Unit): com.example.android.protobuftest.proto.connectrpc.eliza.v1.IntroduceRequest =
  com.example.android.protobuftest.proto.connectrpc.eliza.v1.IntroduceRequestKt.Dsl._create(com.example.android.protobuftest.proto.connectrpc.eliza.v1.IntroduceRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * IntroduceRequest asks Eliza to introduce itself to the named user.
 * ```
 *
 * Protobuf type `connectrpc.eliza.v1.IntroduceRequest`
 */
public object IntroduceRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.android.protobuftest.proto.connectrpc.eliza.v1.IntroduceRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.android.protobuftest.proto.connectrpc.eliza.v1.IntroduceRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.android.protobuftest.proto.connectrpc.eliza.v1.IntroduceRequest = _builder.build()

    /**
     * `string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.android.protobuftest.proto.connectrpc.eliza.v1.IntroduceRequest.copy(block: com.example.android.protobuftest.proto.connectrpc.eliza.v1.IntroduceRequestKt.Dsl.() -> kotlin.Unit): com.example.android.protobuftest.proto.connectrpc.eliza.v1.IntroduceRequest =
  com.example.android.protobuftest.proto.connectrpc.eliza.v1.IntroduceRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

