// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/eliza.proto

package com.example.android.protobuftest.proto.connectrpc.eliza.v1;

public interface IntroduceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connectrpc.eliza.v1.IntroduceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
